
CREATE TABLE USERS 
(
  ID NUMBER NOT NULL 
, USERNAME VARCHAR2(50) NOT NULL UNIQUE
, EMAIL VARCHAR2(50) UNIQUE
, NAME VARCHAR2(100) 
, TYPE VARCHAR2(20) NOT NULL 
, PASSWORD VARCHAR2(100) NOT NULL 
, CONSTRAINT USERS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE COURSE 
(
  ID NUMBER NOT NULL 
, STARTDATE DATE 
, ENDDATE DATE  
, DESCRIPTION VARCHAR2(250) 
, NAME VARCHAR2(100) 
, CONSTRAINT COURSE_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);


CREATE TABLE ENROLLMENT 
(
  COURSEID NUMBER NOT NULL 
, USERID NUMBER NOT NULL 
, ENROLLMENTDATE TIMESTAMP 
, CANCELLED NUMBER(1) DEFAULT 0 
, CANCELLATIONREASON VARCHAR2(250) 
, CONSTRAINT ENROLLMENT_PK PRIMARY KEY 
  (
    COURSEID 
  , USERID 
  )
  ENABLE 
);

CREATE TABLE TEACHERSPERCOURSE 
(
  TEACHERID NUMBER NOT NULL 
, COURSEID NUMBER NOT NULL 
, CONSTRAINT TEACHERSPERCOURSE_PK PRIMARY KEY 
  (
    TEACHERID 
  , COURSEID 
  )
  ENABLE 
);

CREATE TABLE SESSIONS 
(
  ID NUMBER NOT NULL 
, DAY VARCHAR2(20) 
, STARTTIME TIMESTAMP 
, COURSEID NUMBER 
, ENDTIME TIMESTAMP 
, CONSTRAINT SESSIONS_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE SESSIONS
ADD CONSTRAINT COURSEID FOREIGN KEY
(
  COURSEID 
)
REFERENCES COURSE
(
  ID 
)
ENABLE;



INSERT INTO "STUDENTSCH"."USERS" (ID, USERNAME, EMAIL, NAME, TYPE, PASSWORD) VALUES ('1', 'teacher1', 'teacher1@ss.com', 'teacherName', 'teacher', '$2a$10$eO946eZIEoqeYnTx8SQ0Eexd39ai1iDN.Y8gnC0Mo65T3wxucgOYa')
INSERT INTO "STUDENTSCH"."USERS" (ID, USERNAME, EMAIL, NAME, TYPE, PASSWORD) VALUES ('2', 'teacher2', 'teacher2@ss.com', 'teacherName2', 'teacher', '$2a$10$eO946eZIEoqeYnTx8SQ0Eexd39ai1iDN.Y8gnC0Mo65T3wxucgOYa');
INSERT INTO "STUDENTSCH"."USERS" (ID, USERNAME, EMAIL, NAME, TYPE, PASSWORD) VALUES ('3', 'teacher3', 'teacher3@ss.com', 'teacherName3', 'teacher', '$2a$10$eO946eZIEoqeYnTx8SQ0Eexd39ai1iDN.Y8gnC0Mo65T3wxucgOYa');
INSERT INTO "STUDENTSCH"."USERS" (ID, USERNAME, EMAIL, NAME, TYPE, PASSWORD) VALUES ('5', 'student5', 'student5@ss.com', 'studentName5', 'student', '$2a$10$eO946eZIEoqeYnTx8SQ0Eexd39ai1iDN.Y8gnC0Mo65T3wxucgOYa');
INSERT INTO "STUDENTSCH"."USERS" (ID, USERNAME, EMAIL, NAME, TYPE, PASSWORD) VALUES ('6', 'student6', 'student6@ss.com', 'studentName6', 'student', '$2a$10$eO946eZIEoqeYnTx8SQ0Eexd39ai1iDN.Y8gnC0Mo65T3wxucgOYa');



INSERT INTO "STUDENTSCH"."COURSE" (ID, STARTDATE, ENDDATE, DESCRIPTION, NAME) VALUES ('1', TO_DATE('2024-10-01 19:31:59', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-12-31 19:32:12', 'YYYY-MM-DD HH24:MI:SS'), 'java Course DESC', 'Java Course');
INSERT INTO "STUDENTSCH"."COURSE" (ID, STARTDATE, ENDDATE, DESCRIPTION, NAME) VALUES ('2', TO_DATE('2024-08-01 19:32:21', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2024-11-30 19:32:28', 'YYYY-MM-DD HH24:MI:SS'), 'php course DESC', 'PHP Course');


INSERT INTO "STUDENTSCH"."ENROLLMENT" (COURSEID, USERID, ENROLLMENTDATE) VALUES ('1', '5', TO_TIMESTAMP('2024-07-21 19:15:34.645545200', 'YYYY-MM-DD HH24:MI:SS.FF'));

INSERT INTO "STUDENTSCH"."SESSIONS" (ID, DAY, STARTTIME, COURSEID, ENDTIME) VALUES ('1', 'Monday', TO_TIMESTAMP('2024-10-07 18:00:00.314908100', 'YYYY-MM-DD HH24:MI:SS.FF'), '1', TO_TIMESTAMP('2024-10-07 20:00:00.277911900', 'YYYY-MM-DD HH24:MI:SS.FF'));

INSERT INTO "STUDENTSCH"."TEACHERSPERCOURSE" (TEACHERID, COURSEID) VALUES ('2', '1');
